# Author: Lucas Vilas-Boas
# Year: 2025
# Repo: https://github.com/lucoiso/luvk

SET(VULKAN_HEADERS_ENABLE_TESTS OFF CACHE BOOL "" FORCE)
SET(VULKAN_HEADERS_ENABLE_INSTALL OFF CACHE BOOL "" FORCE)
SET(VULKAN_HEADERS_ENABLE_MODULE OFF CACHE BOOL "" FORCE)

FETCHCONTENT_DECLARE(vulkan
                     GIT_REPOSITORY https://github.com/KhronosGroup/Vulkan-Headers.git
                     GIT_TAG v1.4.335
)
FETCHCONTENT_MAKEAVAILABLE(vulkan)

TARGET_INCLUDE_DIRECTORIES(Vulkan-Headers INTERFACE ${vulkan_SOURCE_DIR}/include)

SET(VOLK_HEADERS_ONLY OFF CACHE BOOL "" FORCE)
SET(VOLK_INSTALL OFF CACHE BOOL "" FORCE)
SET(VOLK_PULL_IN_VULKAN OFF CACHE BOOL "" FORCE)
SET(VOLK_NAMESPACE OFF CACHE BOOL "" FORCE)

FETCHCONTENT_DECLARE(volk
                     GIT_REPOSITORY https://github.com/zeux/volk.git
                     GIT_TAG 34d6fff593000645e6a0415a888198767c288842
)
FETCHCONTENT_MAKEAVAILABLE(volk)

TARGET_SOURCES(volk PRIVATE ${volk_SOURCE_DIR}/volk.c)

IF (WIN32)
    TARGET_COMPILE_DEFINITIONS(volk PUBLIC VK_USE_PLATFORM_WIN32_KHR)
ELSEIF (MACOS)
    TARGET_COMPILE_DEFINITIONS(volk PUBLIC VK_USE_PLATFORM_MACOS_MVK)
ELSEIF (UNIX)
    TARGET_COMPILE_DEFINITIONS(volk PUBLIC VK_USE_PLATFORM_XCB_KHR)
ENDIF (WIN32)

TARGET_COMPILE_DEFINITIONS(volk PUBLIC VK_NO_PROTOTYPES=1)

TARGET_INCLUDE_DIRECTORIES(volk PUBLIC ${volk_SOURCE_DIR})
TARGET_LINK_LIBRARIES(volk PUBLIC Vulkan-Headers)

TARGET_LINK_LIBRARIES(${LIBRARY_NAME} PUBLIC volk)